version: 2.1
jobs:
  trivy-scan:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the image with trivy
          command: trivy image --no-progress --exit-code 1 --exit-on-eol 2 --vuln-type HIGH,CRITICAL pgschk/foundryvtt-containerized:latest
workflows:
  scan:
    triggers:
       - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - trivy-scan
