version: 2.1

parameters:
  run-schedule:
      type: boolean
      default: false

jobs:
  trivy-scan:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the image with trivy
          command: trivy image --no-progress --exit-code 1 --exit-on-eol 2 --severity HIGH,CRITICAL pgschk/foundryvtt-containerized:latest

workflows:
  scan:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - trivy-scan