name: Automated Testing CI

on:
  push:
    branches:
      - main
      - more-ci
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

env:
    IMAGE_NAME: pgschk/foundryvtt-containerized
    TEST_TAG: pgschk/foundryvtt-containerized:test
concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.CI_FOUNDRYVTT_DOWNLOAD_URL }}"
      - uses: actions/checkout@v3

      # # Workaround: https://github.com/docker/build-push-action/issues/461
      # - name: Setup Docker buildx
      #   uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      # # Build Docker image with Buildx
      # # https://github.com/docker/build-push-action
      # - name: Build and export Docker image
      #   id: build-and-export
      #   uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
      #   with:
      #     context: .
      #     push: false
      #     load: true
      #     tags: ${{ env.TEST_TAG }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      # Run container-structure-test
      # https://github.com/marketplace/actions/container-structure-test-action
      # - name: Run container-structure-tests
      #   uses: plexsystems/container-structure-test-action@v0.3.0
      #   with:
      #     image: ${{ env.TEST_TAG }}
      #     config: tests/container-structure-test/tests.yml

      - name: Run all tests
        run: ./tests/tests.sh