name: Trivy Vulnerability Scan

on:
  push:
    branches:
      - 'main'
      - trivy
  pull_request:
    branches:
      - 'main'

jobs:
  scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image from Dockerfile
        run: |
          docker build -t pgschk/foundryvtt-containerized:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'pgschk/foundryvtt-containerized:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'