name: Daily Vulnerability Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '40 15 * * *'
jobs:
  scan:
    name: Daily Trivy Vulnerability Scan (CRITICAL,HIGH)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'pgschk/foundryvtt-containerized:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          version: v0.74.0
        env:
          TRIVY_EXIT_ON_EOL: '2'
          TRIVY_DISABLE_VEX_NOTICE: 'true'
          TRIVY_SHOW_SUPPRESSED: 'true'
